### ISSUE TITLE
Demo on latest Chrome shows nothing and does not validate input?

### ISSUE THREAD

**Issue by rdehuyss** [jonataswalker/timepicker.js#36]
Hi,

I tried your demo on the latest chrome (68.0.3440) and no timepicker is available...

Am I missing something?

**Comment by jonataswalker** [comment]
Hi @rdehuyss 

Did you check your console?
Here I have 404 errors. I'll change from Rawgit to JSFiddle.

**Comment by jonataswalker** [comment]
Done ... https://jsfiddle.net/jonataswalker/fgyk86on/
