### ISSUE TITLE
Timepicker leave away from input

### ISSUE THREAD

**Issue by jozefmizerik** [jonataswalker/timepicker.js#43]
On input click, I think timepicker should be shown next to input field. It works like expected if the input is in main view of document. If the input is situated lower (we need to scroll to see it) and we click it, the timepicker is shown more higher, in the initial view page.
![screen2](https://user-images.githubusercontent.com/40183056/75587514-eaca7900-5a76-11ea-88f4-8fb326ebbbb3.png)

**Comment by wiulma** [comment]
I cloned the project, build locally and use the compiled local version instead of the cdn version.
It seems a little bit better about vertical position issue.
But it seems there is still something to fix in horizontal position, when you have horizontal scrolls.

**Comment by jonataswalker** [comment]
Oh I see, this need to be fixed. Are you able to provide a PR?

**Comment by wiulma** [comment]
I didn't fixed code yet. I'll do it asap

**Comment by skaptemalac** [comment]
Is it already possible to use package or the bug is remaining?

**Comment by EngineerSE** [comment]
Is this bug resolved? As im still facing this issue

**Comment by jozefmizerik** [comment]
Hi, nobody have fixxed the bug, yet? If somebody did, please make pull request because I need the library for my thesis, but I'm not able to fix it :(

**Comment by wiulma** [comment]
the sample in test/e2e seems working.
So...we need an example with the issue in order to fix it

**Comment by jonataswalker** [comment]
Can anyone test this bug against released v3?

**Comment by awantengah** [comment]
I try use v3, on desktop, it's display on right position..
but in mobile not..

**Comment by Avalancs** [comment]
The issue still happens in 3.0.0. I used it on a Joomla page, with the input field behind a tab made with Bootstrap.
![timepicker_issue](https://user-images.githubusercontent.com/18668703/91440359-c6592900-e86e-11ea-9d1c-b46ee3ca0fa3.jpg)

**Comment by Avalancs** [comment]
In the `show()` function, changing this line:
```
var targetOffset = picker.target.offset;
```
To the following:
```
var targetOffset = getOffset(picker.target.element);
```
Solves the problem for me
