### ISSUE TITLE
Timepicker stop working

### ISSUE THREAD

**Issue by Brupes** [jonataswalker/timepicker.js#45]
hello,
describing first of all what is happening with me, I am using node.js with react implementation and i added your timepicker in my project because it was the best i founded but when an update occurs in the react state i lose the timepicker so i can not use it again. i decided to execute the timepicker constructor again (in the componentDidUpdate() function) and i was now able to open the timepicker but i could not select the time yet...
i decided to check your code and i did some tests too when i noticed that if i execute the constructor more than one time the code breaks for some reason (probably because of the classname index being the first. i did not checke that part of code. just thinking about it)
what i did to solve it was basically deleting the div with all their content before adding the new one.
if already exists one div with that name, it is deleted to create a new one with the new content and functions
sorry for my bad english btw...

here is the before and after my edit so you can add it to your code later if you decide to.

line 543 (BEFORE MY EDIT)
container.style.zIndex = getMaxZIndex() + 10;
container.style.visibility = 'hidden';
document.body.appendChild(container);

line 543 (AFTER MY EDIT)
container.style.zIndex = getMaxZIndex() + 10;
container.style.visibility = 'hidden';
let auxiliar = document.getElementById(container_id);
if (auxiliar != null)
    document.body.removeChild(auxiliar);
document.body.appendChild(container);

**Comment by jonataswalker** [comment]
Hi @Brupes going well?

I'm in the middle of a complete refactor of this "plugin" and will look closer to this issue. Are you able to create a reproducible fiddle to make things easier?

**Comment by jonataswalker** [comment]
Hey @Brupes 

How about released v3?

**Comment by Brupes** [comment]
hi @jonataswalker 
now the timepicker is displayed but i am not able to interact with it.
what is happening is that it is creating so many timepickers that it loses the control of it.
in the atrached printscreen you can see that it is interacting with a lot of divs. i am using only one timepicker and in each update it creates a lot of them. the situation in the picture occurs when i click in the "button" to show the timepicker
i changed it to the componentdidMount and it happens the same thing...

i belive that the problem here are the updates in react...
maybe you can try to create a system that works based in the target id...
if we try to create a new timepicker to interact with a target, we just delete the old one to create a new one... it is the idea behind the fix i did before. i did not test it with more than one timepicker but i belive that if i try to use more than one timepicker it will work only with the last one. if we add the target id to the created div so we delete that one instead of the last one, maybe we can get some control on it...

i do not know if i was able to tell you my idea to fix it but if not tell me. i can try to explain better.
i am only on the second year at school. now on third.... i am starting in this area :)

trying to use examples to explain in another way...
i am creating a fivem server now and for markers, for example, i have a list of marker positions created based on the name of the "parent" resource. the callers (i do not know how to name the "parent" resources) can update only their part of the list. it is like a database where the client can work only on its tables...

i hope this can help you fixing it.
the project where i was using the timepicker is already finished but i can still test your updates on it. just ask for it.

sorry again for my english. portuguese is easier for me :)
regards,
Bruno

![Anotação 2020-07-25 123607](https://user-images.githubusercontent.com/25111697/88456681-7bb34e00-ce77-11ea-80a1-6d1051593227.png)

**Comment by Brupes** [comment]
i decided to test it more and i was using the old version... it did not updated and i did not noticed it :/
i will test it again but with the last version this time. sorry for the repeated comment...

**Comment by Brupes** [comment]
hi @jonataswalker 
i tested it now and it is working well but it is spaming the DOM with new divs every time... because of the structure of the page i am using, it is not wiping the dom when i move the user to another route so once i go back to the route where i use the timepicker, a new div is created but it is working now. there's just that "spam" to solve...

**Comment by Brupes** [comment]
i forgot to say...
it can be marked as solved now because the main problem is already solved. the spam is a secondary one
regards,
bruno

**Comment by jonataswalker** [comment]
I'm glad to hear. Thanks for the feedback.
