### ISSUE TITLE
latest from CDN brings v2.2.0

### ISSUE THREAD

**Issue by quammy** [jonataswalker/timepicker.js#53]
Hi, can you please fix [//cdn.jsdelivr.net/timepicker.js/latest/timepicker.min.js](url) to show the latest version (and make sure code is of latest version) as it now brings back this:
```
/*!
 * timepicker.js - v2.2.0
 * A lightweight, customizable, TimePicker. Zero dependencies.
 * https://github.com/jonataswalker/timepicker.js
 * Built: Sat Jan 28 2017 15:26:36 GMT-0200 (BRST)
 */
```

Thanks

**Comment by jimaek** [comment]
Thats the old format URL. jsDelivr now updates automatically from NPM and the new format would be

https://cdn.jsdelivr.net/npm/timepicker.js@latest/dist/timepicker.min.js
or
https://cdn.jsdelivr.net/npm/timepicker.js@latest

**Comment by quammy** [comment]
Thanks @jimaek , so you only need to update the link on your readme.md file...
Where can I find the latest css files?

**Comment by jimaek** [comment]
What css files? This project doesnt seem to publish them to npm https://cdn.jsdelivr.net/npm/timepicker.js@latest/

**Comment by jimaek** [comment]
Oh I see there were present in 2.x
You can find them here https://cdn.jsdelivr.net/npm/timepicker.js@2.6.0/dist/

**Comment by quammy** [comment]
Thanks, cheers.
