### ISSUE TITLE
Document/fix .show() function

### ISSUE THREAD

**Issue by marza91** [jonataswalker/timepicker.js#7]
Tried to programatically open the dialog using the .show function, but couldn't get it to work. First, I tried to create a dialog ("this" is an input element, also tried to reference by ID-string):
```
var vTimePicker = new TimePicker(this, {
    theme: 'dark',
    lang: 'en'
});
vTimePicker.show();
```

This didn't work, got "Can't evaluate: @param undefined (timepicker.js:393)" in the show function.
Checked the code, and seemed like the show-function expects a "target" like the constructor. So I tried to pass the element, but then I get "Cannot read property 'element' of undefined (timepicker.js:625)". Same when I pass the id of my element as string.

It fails on "Internal.prototype.show" which apparently expects an id/index in an array of elements, so I tried .show(0);
No luck: Can't evaluate: @param 0 (timepicker.js:393). Now it fails in the evaluate-function where it wants the target/id to be an element or string.

Am I using the .show()-function wrong, or is this a bug? Some more documentation on the .show()-function would be appreciated :)

EDIT: Code formatting

EDIT 2:
Using Chromium Version 51.0.2704.84 (64-bit)
TimePicker:
 * Version: v2.0.0
 * Built: 2016-04-20T22:20:15-0300

**Comment by jonataswalker** [comment]
Yeah, this is buggy. Thanks @marza91 

See #9
